"""Export the dashboard's data from the dbt warehouse.

Run from the repo root after `uv run dbt build`:
    uv run python scripts/export.py

Reads rpt_monthly_retention_summary and writes docs/data.js. It's a .js file rather
than .json so docs/index.html also works when opened straight from disk: browsers
block fetch() on file:// pages, but load <script> tags fine.
"""
import argparse
import datetime
import json
from pathlib import Path

import duckdb

COLUMNS = [
    "cohort_month",
    "activity_month",
    "months_since_cohort",
    "country",
    "acquisition_taxonomy",
    "active_customers",
    "new_customers",
    "continuing_customers",
    "returning_customers",
    "churned_customers",
]


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--db", default="warehouse.duckdb", help="DuckDB file built by dbt")
    parser.add_argument("--out", default="docs/data.js", help="output path")
    args = parser.parse_args()

    con = duckdb.connect(args.db, read_only=True)
    rows = con.sql(
        f"""
        select
            strftime(cohort_month, '%Y-%m')   as cohort_month,
            strftime(activity_month, '%Y-%m') as activity_month,
            {", ".join(COLUMNS[2:])}
        from rpt_monthly_retention_summary
        order by activity_month, cohort_month, country, acquisition_taxonomy
        """
    ).fetchall()
    latest_complete_churn_month, latest_month = con.sql(
        """
        select
            strftime(max(activity_month) filter (where is_churn_complete), '%Y-%m'),
            strftime(max(activity_month), '%Y-%m')
        from rpt_monthly_retention_summary
        """
    ).fetchone()
    con.close()

    payload = {
        "meta": {
            "generated_at": datetime.date.today().isoformat(),
            "latest_month": latest_month,
            "latest_complete_churn_month": latest_complete_churn_month,
        },
        "columns": COLUMNS,
        "rows": [list(row) for row in rows],
    }

    out = Path(args.out)
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(
        "// Generated by scripts/export.py - do not edit by hand.\n"
        f"window.RETENTION_DATA = {json.dumps(payload, separators=(',', ':'))};\n",
        encoding="utf-8",
    )
    print(f"Wrote {len(rows):,} rows to {out} ({out.stat().st_size / 1024:,.0f} KB)")


if __name__ == "__main__":
    main()
